-- 蔵書スキーマ
DROP SCHEMA IF EXISTS 蔵書 CASCADE;
CREATE SCHEMA 蔵書;

CREATE TABLE 蔵書.品目
(
  書籍番号 VARCHAR(20) PRIMARY KEY ,
  タイトル VARCHAR(100) NOT NULL ,
  著者 VARCHAR(40) NOT NULL,
  登録日時 TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE 蔵書.蔵書
(
  蔵書番号 INTEGER PRIMARY KEY,
  書籍番号 VARCHAR(20) NOT NULL REFERENCES 蔵書.品目 (書籍番号),
  登録日時 TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 会員スキーマ
DROP SCHEMA IF EXISTS 会員 CASCADE;
CREATE SCHEMA 会員;

CREATE TABLE 会員.会員種別
(
  名称 VARCHAR(4) PRIMARY KEY
);

INSERT INTO 会員.会員種別
  (名称)
VALUES
  ('一般'),
  ('小中学生')
;

CREATE TABLE 会員.会員
(
  会員番号 INTEGER PRIMARY KEY,
  氏名   VARCHAR(40) NOT NULL,
  会員種別 VARCHAR(4)  NOT NULL REFERENCES 会員.会員種別 (名称),
  登録日時 TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 貸出スキーマ
DROP SCHEMA IF EXISTS 貸出 CASCADE;
CREATE SCHEMA 貸出;

CREATE TABLE 貸出.貸出
(
  蔵書番号 INTEGER UNIQUE NOT NULL REFERENCES 蔵書.蔵書 (蔵書番号),
  会員番号 INTEGER NOT NULL REFERENCES 会員.会員 (会員番号),
  PRIMARY KEY (蔵書番号, 会員番号),
  貸出日 DATE NOT NULL,
  登録日時 TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);